import type { SiteConfig } from '~/types'

const config: SiteConfig = {
  site: 'https://blog.hemelo.fyi',
  title: 'Henrique Melo Blog',
  description:
    'A coder-ready Astro blog theme with 59 of your favorite color schemes to choose from',
  author: 'Henrique Melo',
  tags: ['Astro', 'Terminal', 'Theme', 'hemelo', 'henriquemelo', 'hemelo.fyi', 'blog', 'software engineer', 'developer', 'product manager', 'Henrique Melo', 'software', 'developer', 'engineer'],
  socialCardAvatarImage: './src/content/avatar.jpeg',
  font: 'Montserrat Variable',
  pageSize: 6,
  trailingSlashes: false,
  navLinks: [
    {
      name: 'Home',
      url: '/',
    },
    {
      name: 'About',
      url: '/about',
    },
    {
      name: 'Archive',
      url: '/posts',
    },
    {
      name: 'GitHub',
      url: 'https://github.com/hemelo',
      external: true,
    },
    {
      name: 'Resume',
      url: 'https://resume.hemelo.fyi',
      external: true,
    },
  ],
  themes: {
    mode: 'select',
    default: 'github-light',
    include: [
      'andromeeda',
      'aurora-x',
      'ayu-dark',
      'catppuccin-frappe',
      'catppuccin-latte',
      'catppuccin-macchiato',
      'catppuccin-mocha',
      'dark-plus',
      'dracula',
      'dracula-soft',
      'everforest-dark',
      'everforest-light',
      'github-dark',
      'github-dark-default',
      'github-dark-dimmed',
      'github-dark-high-contrast',
      'github-light',
      'github-light-default',
      'github-light-high-contrast',
      'gruvbox-dark-hard',
      'gruvbox-dark-medium',
      'gruvbox-dark-soft',
      'gruvbox-light-hard',
      'gruvbox-light-medium',
      'gruvbox-light-soft',
      'houston',
      'kanagawa-dragon',
      'kanagawa-lotus',
      'kanagawa-wave',
      'laserwave',
      'light-plus',
      'material-theme',
      'material-theme-darker',
      'material-theme-lighter',
      'material-theme-ocean',
      'material-theme-palenight',
      'min-dark',
      'min-light',
      'monokai',
      'night-owl',
      'nord',
      'one-dark-pro',
      'one-light',
      'plastic',
      'poimandres',
      'red',
      'rose-pine',
      'rose-pine-dawn',
      'rose-pine-moon',
      'slack-dark',
      'slack-ochin',
      'snazzy-light',
      'solarized-dark',
      'solarized-light',
      'synthwave-84',
      'tokyo-night',
      'vesper',
      'vitesse-black',
      'vitesse-dark',
      'vitesse-light',
    ],
    overrides: {},
  },
  socialLinks: {
    github: 'https://github.com/hemelo',
    mastodon: '',
    email: 'hemelo@pm.me',
    linkedin: 'https://linkedin.com/in/henriquefcmelo',
    bluesky: '',
    twitter: 'https://x.com/hemelodev',
    rss: true,
  },
  giscus: {
    repo: 'hemelo/blog',
    repoId: 'R_kgDOPnGrBg',
    category: 'General',
    categoryId: 'DIC_kwDOPnGrBs4CuyAL',
    reactionsEnabled: true,
  },
  characters: {
    owl: '/owl.webp',
    unicorn: '/unicorn.webp',
    duck: '/duck.webp',
  },
}

export default config
